name: cd
on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - run: npm ci
      - run: npm run bld
      - uses: JS-DevTools/npm-publish@v2.2.2
        with:
          token: ${{ secrets.NPM_TOKEN }}
