name: cd
on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - name: Install dependencies
        run: npm ci
      - name: Build output
        run: npm run build
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
