name: cd
on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Volta
        uses: volta-cli/action@v4.2.1
      - name: Install dependencies
        run: npm ci
      - name: Build output
        run: npm run build
      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
