name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - run: npm ci
      - run: npm run format
      - run: npm run lint
      - run: npm run test