name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - run: npm ci
      - run: npm run fmt
      - run: npm run lnt
      - run: npm run test