name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - run: npm ci
      - run: npm run lint
      - run: npm run test