name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - run: npm ci
      - run: npm run fmt
      - run: npm run lnt
      - run: npm run test