name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Volta
        uses: volta-cli/action@v4.1.1
      - name: Install dependencies
        run: npm ci
      - name: Lint codebase
        run: npm run lint
      - name: Test codebase
        run: npm run test
