name: ci
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - run: pnpm lint
      - run: pnpm test