name: ci
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - run: npm ci
      - run: npm run lint
      - run: npm run test