name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test